translate = input("Enter some text: ")
translate = translate.replace("a", "4")
translate = translate.replace("b", "8")
translate = translate.replace("e", "3")
translate = translate.replace("l", "1")
translate = translate.replace("o", "0")
translate = translate.replace("s", "5")
translate = translate.replace("t", "7")
print(translate)
